### ISSUE TITLE
Evading attacks out of sight - When standing

### ISSUE THREAD

**Issue by KeithSammut** [glest/glest-source#144]
What if, when a unit (ex: swordman) is standing, and is attacked by another unit (ex: catapult) which is out of its sight, exactly before the attack starts, the attacked unit (the swordman) moves away (As if it (the swordman) saw the attacker (the catapult), and it only has move command (like the worker does when it sees an enemy)).

This should be helpful when short sighted melee units are attacked by catapults, or some archers out of the blues.

**Comment by mathusummut** [comment]
This will not be implemented for performance reasons.
