### ISSUE TITLE
enlarged icons are a little blurry

### ISSUE THREAD

**Issue by andy5995** [glest/glest-source#168]
@Jammyjamjamman noticed the enlarged icons on the right are a little blurry due to the rescaling

**Comment by linux-player9** [comment]
Will we have an option to rescale the interface ? So that anyone will be able to increase or decrease icons and all other things ?

**Comment by andy5995** [comment]
@linux-player9 We would only consider that if it seemed like that feature was in high-demand. If you have a specific request, you are welcome to open a separate ticket.
