### ISSUE TITLE
Move IRC server and channel to glest.ini

### ISSUE THREAD

**Issue by andy5995** [glest/glest-source#177]
Since ZG is an *engine*, I suggest adding 2 options to glest.ini.

ircServer
ircChannel

This would be an easy change, but low-priority of course.

Once the options are added to glest.ini, users could customize them (if they choose) in their glestuser.ini

glest.ini would hold the default IRC server and channel.

The hard-coded values would be removed from the source code.

**Comment by mathusummut** [comment]
[This is now fixed.](https://github.com/glest/glest-source/commit/e248eddbf910ec87c7ba471762c56a0ed0e2a3a8)
