### ISSUE TITLE
ZG incorrectly detects wrong router setup

### ISSUE THREAD

**Issue by andy5995** [glest/glest-source#189]
While testing, after successfully running a server several times within 10 minutes (not playing a game, but just running a server so I can connect to with a client locally), now ZG incorrectly detects a wrong router setup.

```
Trying to connect to '104.235.241.67' using port '61357'...
socket_connect() failed.
 Reason: (111) Connection refused
wrong router setup
*ERROR* [2018-07-11 13:03:46] In [menu_state_custom_game.cpp::simpleTaskForMasterServer Line 3869] error checking response from masterserver elapsed seconds = 9.00 / 15
Response:
Trying to connect to '104.235.241.67' using port '61357'...
socket_connect() failed.
 Reason: (111) Connection refused
wrong router setup
```
![image](https://user-images.githubusercontent.com/16764864/42591121-5f70f5b0-850b-11e8-8a56-b670412b8cd9.png)

I don't know if the origin of this bug lies within the source code or the code from the [master server](https://github.com/ZetaGlest/zetaglest-masterserver).

I don't know how to reproduce it other than repeatedly running a server. (choosing custom game -> checking the box for "publish on master server"

**Comment by andy5995** [comment]
I had to reboot to fix that.

It happened again afterward, after more testing. However, I found that when I switch to testing with a headless server, it doesn't reproduce. It's apparently only a problem if hosting via *LAN Game* or checking the box for "publish to master server" from the custom game set-up menu.

I'm on Debian 9 Linux, using the latest build.

**Comment by mathusummut** [comment]
I can confirm that this is still an issue.
