### ISSUE TITLE
when joining a running game, new players should only be allowed to select an observer slot

### ISSUE THREAD

**Issue by andy5995** [glest/glest-source#193]
when joining a running game, new players should only be allowed to select an observer slot

If joining a running game is allowed (by checking the option from the custom game set-up menu, new players are allowed to take the place of an AI.

While that may sometimes be desirable, other times it would just be a nuisance.

**Comment by mathusummut** [comment]
But AI takes over network slots when a player has left, so to be able to reclaim their position, they must use an AI network slot.
