### ISSUE TITLE
if units are greyed out, a distinction needs to be made why they're disabled

### ISSUE THREAD

**Issue by andy5995** [glest/glest-source#218]
@mathusummut did a recent great patch that disables the option to produce a unit if the player doesn't have enough cash. But they "greying" out effect is the same as if the unit can't be produced because it requires an upgrade.

There are different ways to implement this, the simplest one would be best for now. Probably just making the color a bright or dark red. or a padlock on units that don't meet upgrade-requirements yet.

**Comment by arthurgsf** [comment]
I would like to pick this

**Comment by andy5995** [comment]
hi @arthurgsf 

Thanks for the offer. For a patch like this, you will need to discuss it with us through the process periodically in [our chat room](https://discord.gg/WaAaXS7)

**Comment by mathusummut** [comment]
[This is now fixed](https://github.com/glest/glest-source/commit/1ad62453246288ea1bc742f3acf7fa225f4388bd)
