### ISSUE TITLE
Allow players to view Freenode connection messages

### ISSUE THREAD

**Issue by andy5995** [glest/glest-source#261]
>One thought I had related to this IRC problem @linux-player9  is having.. it may be worth it to allow the Freenode MOTD to display after connecting. It could help with debugging later, and perhaps it's just good to show it, because we're using their network.
For example, this appears now when I connect to Freenode in my Irc client 

For example, this appears now when I connect to Freenode in my Irc client

 ```-freenode-connect- Due to the persistent ongoing spam, all new connections are being set +R (block messages from unidentified users) and will be scanned for vulnerabilities. This will not harm your computer, and vulnerable hosts will be notified.```

I figure that the MOTD would just show in the lobby, (as opposed to a terminal, since most players aren't going to run ZG in a terminal) in place of the "master server" announcement. Not sure if that screen is scrollable though when messages fill it up...

**Comment by linux-player9** [comment]
So ZetaGlest will not automaticaly try to connect to IRC ane instead users will connect is a button so that Freenode will not block them ?
