### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by WPFilmmaker** [glest/glest-source#294]
First of all thank you @mathusummut for continuing work on this project! I have a question, we had MegaGlest, than ZetaGlest, and now the name is Glest as the original project. I think it is confusing for people since (afaik) it is not the same game. Are you thinking about a new name?What was wrong with ZetaGlest?

**Comment by mathusummut** [comment]
Most of our community agreed that the name "ZetaGlest" was considered too strange for the general public to remember, so we decided to simplify the name and call it "Glest". As far as I can tell, it is confusing only to people who were closely following the project, as the name "ZetaGlest" was removed as if it never existed. Now we need to create a proper Glest website to promote our project.

**Comment by MirceaKitsune** [comment]
I'm okay with the name staying ZetaGlest: It's a good sounding name and most people already know it by this term. Glest would be a bad idea as this is not the original Glest game, which has been dead for roughly a decade now.

**Comment by WPFilmmaker** [comment]
@MirceaKitsune, I have no preferences over the new names, I thought this project was a fork of ZetaGlest (but apparently I am wrong). And Yes the second part of your message is exactly why I opened this ticket suggesting a new name. Even the websites are confusing (glest.io vs glest.org), one read on wikipdia about Glest being dead and later finds this project actively developed called with the same name.

**Comment by mathusummut** [comment]
From my personal point of view, I will not go through the physical pain of renaming the game any more times, it takes days of constant work which is not worth my time at all. That is my stance, if anyone wants to create a new fork, by all means go ahead.

**Comment by ZeoxD** [comment]
wikipedia can be changed in future. 
right now Glest2.0 project is in its infancy , still a long  way to go.
Glest2.0(2019- and so on) is different from glest 1.0 (2003-2008) or whatever.
