### ISSUE TITLE
Flatpak file?

### ISSUE THREAD

**Issue by WPFilmmaker** [glest/glest-source#295]
Right now on has to download the master from github, however all previous forms of *glest has installers. I suggest to create a distro-agnostic installer by using flatpak. MegaGlest (which afaik is not much active anymore) is on flathub.org which is a good showcase for people finding new apps. Once you have a flatpak for Glest you can think about putting it on flathub.org

**Comment by mathusummut** [comment]
Currently, there is a Glest installer for Windows, but for Linux, we are currently using the following one-liner command to install Glest:

`git clone https://github.com/Glest/glest-source.git glest; sudo glest/mk/linux/setup.sh`

If you want, you can help us create an installer package for Linux! If interested, we can discuss on our Discord server: https://discord.gg/WaAaXS7

**Comment by WPFilmmaker** [comment]
Unfortunately I am not a developer, jut an old MG player who found this project after years:D 
I realized you had this instruction on the man page on github but when I saw "(Later, we'll be providing binary packages)." I thought (and still think) flatpak is a good idea for Linux so I would suggest to look into that^^ I will definitively keep on eye on this project!

**Comment by Jammyjamjamman** [comment]
Please checkout https://github.com/glest/io.glest.Glest and https://github.com/glest/snap-packager (these are still WIP but both are working).

**Comment by Jammyjamjamman** [comment]
There's several different linux installers which you can find out about at https://github.com/glest/glest-source
