### ISSUE TITLE
Version differences and steam version

### ISSUE THREAD

**Issue by salvadorc17** [glest/glest-source#296]
Does this has difference with mega glest, or is same steam version and does this can be used to create another standalone game

**Comment by mathusummut** [comment]
This is a newer (and in some ways better) version of MegaGlest, you can view the new changes here:
https://github.com/glest/glest-source/blob/master/ChangeLog.md

**Comment by salvadorc17** [comment]
Still can use it to create standalone game, or any restrictions?

**Comment by mathusummut** [comment]
You can use it to your heart's content :) Just make sure to credit the original creators
