### ISSUE TITLE
Unit Floating Attribute

### ISSUE THREAD

**Issue by KeithSammut** [glest/glest-source#297]
Adding a unit attribute for floating, by limiting the level reachable by the units which have the attribute added.

This is for ships to not sink.

**Comment by mathusummut** [comment]
[This is now added](https://github.com/glest/glest-source/commit/23471ac39d8913ebb091dc812710923b1932e142), the syntax being as follows:
    <float value="true"/>

**Comment by KeithSammut** [comment]
thank you!
