### ISSUE TITLE
Attack commands cannot be queued

### ISSUE THREAD

**Issue by Jammyjamjamman** [glest/glest-source#48]
This bug was inherited from MegaGlest, but I'm not sure it was mentioned there. If you try to queue many attacks, you get a rubberbanding glitch (where units  jump back to their initial position), until the final attack is queued. if you try to queue attacks with other commands, the queue gets reset as soon as the different command is queued.

**Comment by Jammyjamjamman** [comment]
OK, the likely reason for the queue cancellation is the bad code on line 79 of https://github.com/ZetaGlest/zetaglest-source/blob/develop/source/glest_game/type_instances/command.cpp (I say bad because there is an instance variable defined to store a command priority, yet it uses an if statement to decide the priority later). Attacks have "lower priority" than other commands. This means it is cancelled, along with all other low priority commands if another "higher priority" command is issued.

**Comment by andy5995** [comment]
Nice work debugging, @Jammyjamjamman !

For now, I've submitted PR #49 to change the default right-click back to move.

We can revisit it later. I found it harder to use, having to use the "m" key to move units. I always thought that attack being the default would make things better, but I have my doubts.

But as I said, we can think about a change like this later. Sorry, @biels.

**Comment by Jammyjamjamman** [comment]
I think it's more difficult because you have to re-learn default commands, but it's something you'd get used to.

There is one area where it definitely gets harder: when you're trying to retreat. I've thought of a couple of ways to fix this. One is to use "middle" click for move, or to move as soon as you press "m" (to the position of the cursor), rather than "m" + click.

**Comment by andy5995** [comment]
>There is one area where it definitely gets harder: when you're trying to retreat.

That was one of the biggest things I noticed, too.

>I think it's more difficult because you have to re-learn default commands, but it's something you'd get used to.

I agree that was part of my problem. ;) But after switching the default right-click action to attack and then playing that way for a few games, I didn't see a clear advantage . Instead of using the "a" key frequently, I had to use the "m" key. But I did like that units were in attack-mode as soon as they left the barracks.

Do you prefer the default right-click action as "attack"?

**Comment by mathusummut** [comment]
Is this still relevant?

**Comment by andy5995** [comment]
>If you try to queue many attacks, you get a rubberbanding glitch (where units jump back to their initial position), until the final attack is queued. 

Yes.

**Comment by mathusummut** [comment]
[This is finally fixed.](https://github.com/glest/glest-source/commit/5c0a7040133f8c5618de59701245d555a04bae4a)
