### ISSUE TITLE
Should commondata be in the "techs" folder?

### ISSUE THREAD

**Issue by andy5995** [glest/glest-source#69]
Right now, a lot of sounds for zetapack are in

techs/zetapack/commondata/sounds

Should commondata be directly under the techs folder?

This would require changing a little code.

Right now if you want to test a mod and have the zetapack factions present, you have to create a new tech tree, add your mod, then add in the faction links. Your mod may only need to use sounds from commondata.. but that wouldn't be present from your new techtree folder, so the sounds would have to be added (copied).

This is an example of how commondata is used:

https://github.com/ZetaGlest/zetaglest-data/blob/254b3dd645faba8d5c29011b494e7297a23015c7/techs/zetapack/factions/egypt/units/scarab/scarab.xml#L40-L55

**Comment by mathusummut** [comment]
Mods should not rely on the glestpack imo
