### ISSUE TITLE
Implement water-only units

### ISSUE THREAD

**Issue by KeithSammut** [glest/glest-source#84]
The water field should be added, to make production of marine situated scenarios much easier, and to enable new factions to use water. It should be named "any_water" and it would enable naval battles in a normal network game for example.

**Comment by andy5995** [comment]
This is a good idea of course, but may be beyond the scope of this project.

We could keep adding new features, but one of the attractions of this game, I think, is that it doesn't have a million units to micro-manage. For me, an old guy, I have trouble micro-ing the units that already exist! :)

One option would be to implement the feature, so at least it could be used in mods and scenarios, but not having it in the default zetapack. But I am not completely opposed to having it with the default zetapack factions; I think I would leave that up to @mathusummut and @Jammyjamjamman to make the final decision.

**Comment by KeithSammut** [comment]
I agree that it's too vague to imply that naval units should be universally included, because that would primarily require refurbishing of all factions, and secondly as you said an increased complexity which would fuddle the users. My main point is knotted to the scenario building, especially in the Atlantis scenario :P

**Comment by andy5995** [comment]
To build a shipyard, there'd have to be a check.. typically in games, a shipyard is built on a combination of land and water. That shouldn't be a big deal to check.. basically for the surface depth of the cells when trying to build a shipyard.

There'd also have to be a check when producing ships, to make sure the area has enough room for a ship.

And the ship would have to exit the shipyard into the water area.

This is all do-able, but will take time. :)

**Comment by WPFilmmaker** [comment]
+1 this could be epic! Imagine how many new scenarios we could have with water units :D

**Comment by MirceaKitsune** [comment]
I approve of this idea; It's an essential mechanic which neither Glest MegaGlest or GlestAdvanced ever implemented. I presume doing it shouldn't be too hard either: Ship units are simply allowed to navigate only over water, whereas for ports we check whether they touch both water and land... additionally we could support amphibian units which can do both. Personally I'd add 3 options in total:

1. Water or land: The unit can be placed on and navigate over either water or land at any time.
2. Water and land: The unit must touch both water and land at the same time (shipyards).
3. Water only: The unit may only be placed and navigate over water without touching land.

**Comment by mathusummut** [comment]
[This feature is now added.](https://github.com/glest/glest-source/commit/a7d0354ca44cafb9703c3f76f6b1368f8aa9a426)
Glest now has support for "water" and "landwater" field types, where "water" means water only, and "landwater" means the unit can travel across both water and land.

**Comment by biels** [comment]
Wow!! 😎💯
